package Recursion;

import java.util.ArrayList;

public class SubsetsRecursionProblem {

    // > Q1
    /*
     * Given a string, WAM to return all its subsequences in an arraylist. A String
     * is a
     * subsequence of a given String that is generated by deleting some character of
     * a given
     * string without changing its order.
     * Input : abc
     * Output : a, b, c, ab, bc, ac, abc.
     */

    static ArrayList<String> getSubSequence(String str) {
        ArrayList<String> ans = new ArrayList<>();

        if (str.length() == 0) {
            ans.add("");
            return ans;
        }
        char currentChar = str.charAt(0);
        ArrayList<String> smallAns = getSubSequence(str.substring(1));

        for (String ss : smallAns) {

            ans.add(currentChar + ss);
            ans.add(ss);
        }
        return ans;

    }

    // > Q2 Given a string, write a method to print all its subsequences.

    static void printSubSequence(String str, String currentAns) {
        if (str.length() == 0) {
            System.out.print(currentAns + " ");
            return;
        }
        char currentChar = str.charAt(0);
        String remainingStr = str.substring(1);

        printSubSequence(remainingStr, currentAns + currentChar);
        printSubSequence(remainingStr, currentAns);
    }

    // > Q3 Given an array of integers, print sums of all subsets in it. Output sums
    // > can be printed in any order.

    static void subSequenceSum(int[] arr, int n, int idx, int currentSum) {
        if (idx >= n) {
            System.out.print(currentSum + " ");
            return;
        }
        subSequenceSum(arr, n, idx + 1, arr[idx] + currentSum);
        subSequenceSum(arr, n, idx + 1, currentSum);
    }

    public static void main(String[] args) {

        // > Q1
        ArrayList<String> ans = getSubSequence("abc");
        for (String a : ans) {
            System.out.print(a + " ");
        }
        System.out.println();

        // > Q2
        printSubSequence("abc", "");
        System.out.println();

        // > Q3
        int[] arr = { 1, 2, 3 };
        subSequenceSum(arr, arr.length, 0, 0);

    }
}
